language: node_js
node_js:
  - "6"

cache: yarn

before_script:
  - yarn

script:
  - yarn test

deploy:
  provider: npm
  email: "allan.chau@icloud.com"
  api_key: "$NPM_AUTH_TOKEN"
  on:
    branch: master
    tags: true
